#pragma once

#include <cstdint>

namespace gz
{
enum Address {
    SANITY_CHECK,
    INST_CHARACTER_MANAGER,
    INST_GAME_WORLD,
    INST_INPUT_MANAGER,
    INST_NETWORK_PLAYER_MANAGER,
    INST_PLAYER_INFORMATION,
    INST_PHYSICS_SYSTEM,
    INST_ENVIRONMENT_GFX_MANAGER,
    INST_SPAWN_SYSTEM,
    INST_WORLDTIME,
    INST_MAP,
    INST_VEHICLE_MANAGER,
    WND_PROC,
    GRAPHICS_FLIP,
    VAR_GAME_STATE,
    VAR_CLOUD_VISIBILITY,
    ALLOC,
    FREE,
    SPAWN_SYSTEM_SPAWN,
    SPAWN_SYSTEM_PARSE_TAGS,
    SPAWN_SYSTEM_GET_MATCHING_RES,
    SPAWN_VEHICLE_OWNERSHIP_CALLBACK,
    EVENT_SCHEDULER,
    TELEPORT,
    SET_WEATHER_PRESET_FROM_HASH,
    RESTORE_DYNAMIC_WEATHER,
    WEATHER_UPDATE,
    HASHING_FUNC,
    FUNC_VSNPRINTF,
    FUNC_SCRIPT_ERROR_REPORT,
    CONSUME_DEPLOYABLES,
    CONSUME_AMMO,
    PATCH_BUILDING_UI_CHECK_1,
    PATCH_BUILDING_UI_CHECK_2,
    PATCH_BUILDING_CHECK_COLLISION,
    PATCH_BUILDING_CHECK_MASTER,
    PATCH_RESOURCE_CONSUMPTION,
    PATCH_HEALTH_GOD,
    PATCH_INFINITE_FUEL,
    PATCH_HIDE_UI,
    PATCH_DETECTION,
    COUNT,
};

void InitAddresses(bool is_steam);
uintptr_t GetAddress(Address address);
}; // namespace gz